### ISSUE TITLE
CV.sc not included in .quark download

### ISSUE THREAD

**Issue by igormpc** [redFrik/GUICV#1]
hi f0

i got a error trying GreenNanoKontrol2 --
didnt found CV.sc

trying reinstall quark didnt work also --
(so i manually copy it and didnt go this error)

should this class be downloaded/installed with quark? 

thx in advance
igor

**Comment by igormpc** [comment]
didnt get this error on mac high sierra 10.13.6 + sc 3.12.2 + qt 5.15.2 
-- just got it on my archlinux  with sc 3.13.0 + qt 5.15.18 ...

**Comment by redFrik** [comment]
mabe you have an old version of GUICV.
if you installed GUICV with Quarks.install you can try `Quarks.update("https://github.com/redFrik/GUICV")` or `Quarks.checkForUpdates`

**Comment by igormpc** [comment]
worked ok after deleting folders and reinstalling them! thx f0!
