### ISSUE TITLE
error trying GreenFreqScope, GreenMeter & GreenServerMeter

### ISSUE THREAD

**Issue by igormpc** [redFrik/GUICV#2]
hi f0
on these three meters/scope i got errors related to 'levelIndicator':
(just coping here the 1st one...)

ERROR: Message 'levelIndicator' not understood.
RECEIVER:
class GUICV (0x55c170324940) {
  instance variables [19]
    name : Symbol 'GUICV'
    nextclass : instance of Meta_GUICVKnob (0x55c178560b80, size=19, set=5)
    superclass : Symbol 'Object'
    subclasses : nil
    methods : nil
    instVarNames : nil
    classVarNames : instance of SymbolArray (0x55c170324ac0, size=1, set=2)
    iprototype : nil
    cprototype : instance of Array (0x55c170324b80, size=1, set=2)
    constNames : nil
    constValues : nil
    instanceFormat : Integer 0
    instanceFlags : Integer 0
    classIndex : Integer 1387
    classFlags : Integer 0
    maxSubclassIndex : Integer 1387
    filenameSymbol : Symbol '/home/igor/.local/share/SuperCollider/downloaded-quarks/GUICV/scide_scqt/GUICV.sc'
    charPos : Integer 37
    classVarIndex : Integer 58
}
ARGS:
CALL STACK:
	DoesNotUnderstandError:reportError
		arg this = <instance of DoesNotUnderstandError>
	Nil:handleError
		arg this = nil
		arg error = <instance of DoesNotUnderstandError>
	Thread:handleError
		arg this = <instance of Thread>
		arg error = <instance of DoesNotUnderstandError>
	Object:throw
		arg this = <instance of DoesNotUnderstandError>
	Object:doesNotUnderstand
		arg this = <instance of Meta_GUICV>
		arg selector = 'levelIndicator'
		arg args = [*0]
	< FunctionDef in Method GreenMeter:initGreenMeter >  (no arguments or variables)
	< FunctionDef in Method Meta_Collection:fill >
		arg i = 0
	Integer:do
		arg this = 2
		arg function = <instance of Function>
		var i = 0
	Meta_Collection:fill
		arg this = <instance of Meta_Array>
		arg size = 2
		arg function = <instance of Function>
		var obj = [*0]
	GreenMeter:initGreenMeter
		arg this = <instance of GreenMeter>
		arg parent = nil
		arg bounds = nil
		arg target = <instance of Group>
		arg addAction = 'addToTail'
		arg index = 0
		arg numChannels = 2
		arg rate = 30
		var skin = <instance of Event>
		var font = <instance of Font>
		var fontSmall = <instance of Font>
		var fontHeight = 14.0
		var minWidth = 17.0
		var id = nil
		var lastPeaks = nil
		var lastRMSs = nil
		var server = <instance of Server>
	< closed FunctionDef >  (no arguments or variables)
	Interpreter:interpretPrintCmdLine
		arg this = <instance of Interpreter>
		var res = nil
		var func = <instance of Function>
		var code = "Window().layout_(VLayout(But..."
		var doc = nil
		var ideClass = <instance of Meta_ScIDE>
	Process:interpretPrintCmdLine
		arg this = <instance of Main>
^^ ERROR: Message 'levelIndicator' not understood.
RECEIVER: GUICV

i dont know how to fix them...
maybe something wrong with my qt version?

thx in advance
igor

**Comment by igormpc** [comment]
same here:  didnt get this error on mac high sierra 10.13.6 + sc 3.12.2 + qt 5.15.2
-- just got it on my archlinux with sc 3.13.0 + qt 5.15.18 ...

**Comment by redFrik** [comment]
sorry to hear about your troubles.
it's best to install GFX and greenSys using Quarks.install.  then GUICV will be installed automatically.  GUICV is listed as a dependency in the .quarks file.
so please try to delete all greenSys, GFX and GUICV folders and just run...
```
Quarks.install("https://github.com/redFrik/greenSys");
//and or...
Quarks.install("https://github.com/redFrik/GFX");
```

also keep them up to date with `Quarks.checkForUpdates` (take a while to complete)

**Comment by igormpc** [comment]
worked ok after deleting folders and reinstalling them! thx f0!

two more questions:

1. is there a midi learn function already for gfx? i remember you commenting on notam meeting but couldnt find any doc... which key should i press to connect knobs/sliders to cc (2 controllers here, one generic midi and a nanokontrl2...)? 
2. is there a zoom in/out for green scope? 

thx in advance!!
